/*
 * generated by Xtext 2.16.0
 */
package ac.soton.xeventb.ui;

import ac.soton.xeventb.proofassistant.ui.internal.ProofassistantActivator;
import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ProofAssistantExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(ProofassistantActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		ProofassistantActivator activator = ProofassistantActivator.getInstance();
		return activator != null ? activator.getInjector(ProofassistantActivator.AC_SOTON_XEVENTB_PROOFASSISTANT) : null;
	}

}
