/*
 * generated by Xtext 2.16.0
 */
package ac.soton.xeventb.xproofassistant


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XProofAssistantStandaloneSetup extends XProofAssistantStandaloneSetupGenerated {

	def static void doSetup() {
		new XProofAssistantStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
