/**
 * generated by Xtext 2.16.0
 */
package ac.soton.xeventb.ui.contentassist;

import ac.soton.xeventb.ui.contentassist.AbstractProofAssistantProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ProofAssistantProposalProvider extends AbstractProofAssistantProposalProvider {
}
