/**
 * generated by Xtext 2.16.0
 */
package ac.soton.xeventb.xproofassistant.ide;

import ac.soton.xeventb.xproofassistant.ide.AbstractXProofAssistantIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class XProofAssistantIdeModule extends AbstractXProofAssistantIdeModule {
}
