/*
 * generated by Xtext 2.16.0
 */
package ac.soton.xeventb.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class ProofAssistantUiModule extends AbstractProofAssistantUiModule {
}
