/**
 * generated by Xtext 2.16.0
 */
package ac.soton.xeventb.formatting2;

import ac.soton.eventb.emf.proofassistant.Hint;
import ac.soton.eventb.emf.proofassistant.ProofAssistant;
import ac.soton.xeventb.services.ProofAssistantGrammarAccess;
import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class ProofAssistantFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private ProofAssistantGrammarAccess _proofAssistantGrammarAccess;
  
  protected void _format(final ProofAssistant proofAssistant, @Extension final IFormattableDocument document) {
    EList<Hint> _hints = proofAssistant.getHints();
    for (final Hint hint : _hints) {
      document.<Hint>format(hint);
    }
  }
  
  public void format(final Object proofAssistant, final IFormattableDocument document) {
    if (proofAssistant instanceof ProofAssistant) {
      _format((ProofAssistant)proofAssistant, document);
      return;
    } else if (proofAssistant instanceof XtextResource) {
      _format((XtextResource)proofAssistant, document);
      return;
    } else if (proofAssistant instanceof EObject) {
      _format((EObject)proofAssistant, document);
      return;
    } else if (proofAssistant == null) {
      _format((Void)null, document);
      return;
    } else if (proofAssistant != null) {
      _format(proofAssistant, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(proofAssistant, document).toString());
    }
  }
}
