/*
 * generated by Xtext 2.16.0
 */
package ac.soton.xeventb.xproofassistant.ide


/**
 * Use this class to register ide components.
 */
class XProofAssistantIdeModule extends AbstractXProofAssistantIdeModule {
}
