/**
 * generated by Xtext 2.16.0
 */
package ac.soton.xeventb.xproofassistant.scoping;

import ac.soton.xeventb.xproofassistant.scoping.AbstractXProofAssistantScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class XProofAssistantScopeProvider extends AbstractXProofAssistantScopeProvider {
}
