/**
 * generated by Xtext 2.16.0
 */
package ac.soton.xeventb.xproofassistant.ui;

import ac.soton.xeventb.xproofassistant.ui.AbstractXProofAssistantUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class XProofAssistantUiModule extends AbstractXProofAssistantUiModule {
  public XProofAssistantUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
