/**
 * generated by Xtext 2.16.0
 */
package ac.soton.xeventb;

import ac.soton.xeventb.ProofAssistantStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ProofAssistantStandaloneSetup extends ProofAssistantStandaloneSetupGenerated {
  public static void doSetup() {
    new ProofAssistantStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
