/**
 * generated by Xtext 2.16.0
 */
package ac.soton.xeventb;

import ac.soton.xeventb.AbstractProofAssistantRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ProofAssistantRuntimeModule extends AbstractProofAssistantRuntimeModule {
}
