/*
 * generated by Xtext 2.16.0
 */
package ac.soton.xeventb.ui.tests;

import ac.soton.xeventb.proofassistant.ui.internal.ProofassistantActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class ProofAssistantUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return ProofassistantActivator.getInstance().getInjector("ac.soton.xeventb.ProofAssistant");
	}

}
