/**
 * generated by Xtext 2.16.0
 */
package ac.soton.xeventb.ui;

import ac.soton.xeventb.ui.AbstractProofAssistantUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ProofAssistantUiModule extends AbstractProofAssistantUiModule {
  public ProofAssistantUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
