/**
 * generated by Xtext 2.16.0
 */
package ac.soton.xeventb.validation;

import ac.soton.xeventb.validation.AbstractProofAssistantValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ProofAssistantValidator extends AbstractProofAssistantValidator {
}
