/**
 * generated by Xtext 2.16.0
 */
package ac.soton.xeventb.xproofassistant.validation;

import ac.soton.xeventb.xproofassistant.validation.AbstractXProofAssistantValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class XProofAssistantValidator extends AbstractXProofAssistantValidator {
}
