/**
 * generated by Xtext 2.16.0
 */
package ac.soton.xeventb.ide;

import ac.soton.xeventb.ide.AbstractProofAssistantIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ProofAssistantIdeModule extends AbstractProofAssistantIdeModule {
}
