/**
 * generated by Xtext 2.16.0
 */
package ac.soton.xeventb.ide;

import ac.soton.xeventb.ProofAssistantRuntimeModule;
import ac.soton.xeventb.ProofAssistantStandaloneSetup;
import ac.soton.xeventb.ide.ProofAssistantIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class ProofAssistantIdeSetup extends ProofAssistantStandaloneSetup {
  @Override
  public Injector createInjector() {
    ProofAssistantRuntimeModule _proofAssistantRuntimeModule = new ProofAssistantRuntimeModule();
    ProofAssistantIdeModule _proofAssistantIdeModule = new ProofAssistantIdeModule();
    return Guice.createInjector(Modules2.mixin(_proofAssistantRuntimeModule, _proofAssistantIdeModule));
  }
}
