/*
 * generated by Xtext 2.16.0
 */
package ac.soton.xeventb.parser.antlr;

import ac.soton.xeventb.parser.antlr.internal.InternalProofAssistantParser;
import ac.soton.xeventb.services.ProofAssistantGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ProofAssistantParser extends AbstractAntlrParser {

	@Inject
	private ProofAssistantGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalProofAssistantParser createParser(XtextTokenStream stream) {
		return new InternalProofAssistantParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ProofAssistant";
	}

	public ProofAssistantGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ProofAssistantGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
