/*
 * generated by Xtext 2.16.0
 */
package ac.soton.xeventb.xproofassistant.parser.antlr;

import ac.soton.xeventb.xproofassistant.parser.antlr.internal.InternalXProofAssistantParser;
import ac.soton.xeventb.xproofassistant.services.XProofAssistantGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class XProofAssistantParser extends AbstractAntlrParser {

	@Inject
	private XProofAssistantGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalXProofAssistantParser createParser(XtextTokenStream stream) {
		return new InternalXProofAssistantParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "XProofAssistant";
	}

	public XProofAssistantGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XProofAssistantGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
